version: '3'

services:
  app:
    build:
      context: .
    image: ghcr.io/miladrahimi/p-node:${TAG:-stable}
    restart: always
    network_mode: host
    volumes:
      - ./configs/:/app/configs/
      - ./storage/:/app/storage/
