version: "3.8"

services:
  app:
    image: ghcr.io/miladrahimi/p-node:${TAG:-stable}
    restart: always
    network_mode: host
    volumes:
      - ./configs/:/app/configs/
      - ./storage/:/app/storage/
